### ISSUE TITLE
Do not include child margin

### ISSUE THREAD

**Issue by ai** [animakit/animakit-expander#10]
In this example

``` jsx
<AnimakitExpander expanded={true}>
  <div style="height: 100px; margin-bottom: 50px"></div>
</AnimakitExpander>
```

`AnimakitExpander` will have only `100px` height and ignore `50px` margin of child

**Comment by askd** [comment]
Thanks for the issue. Will be done soon

**Comment by askd** [comment]
Done: https://github.com/animakit/animakit-expander/commit/ca9d37f9c8de2f01b06c99b9d14b7c9e3dfbec57
Use version 1.0.13
Have a nice day ;)
