### ISSUE TITLE
No animation on empty body

### ISSUE THREAD

**Issue by ai** [animakit/animakit-expander#4]
Here is my Jade React template:

``` slim
AnimakitExpander( expanded=this.props.type )
  if this.props.type
    .post-error
      = t(this.props.type)
```

On no `this.props.type` component doesn’t set any body to Expander.

As result I have no animation from closed to expanded state (no animation when I add error). But animation is OK when I remove error (expanded → closed state).

I fixed problem by adding a empty body on no error state:

``` slim
AnimakitExpander( expanded=this.props.type )
  if this.props.type
    .post-error
      = t(this.props.type)
  else
    .post-error
```

So expander has issue when we it has no body in some state.

P.S. Amplifr now finally uses Animakit! :) @askd

**Comment by askd** [comment]
Thanks for the issue!
I reworked the component, and now it does not render children when collapsed. At the same time, it monitors dimension of the children. So you might not output children if you do not need them.
Commit: https://github.com/animakit/animakit-expander/commit/c802fcf3e23652fea42fe97916f79b299ca4fcc0
