### ISSUE TITLE
Dynamic duration

### ISSUE THREAD

**Issue by ai** [animakit/animakit-expander#5]
Should we calculate duration dynamically based on body height?

**Comment by askd** [comment]
I added `durationPerPx` property. Use it if you want the duration depended on the content size and calculated dynamically.
Commit: https://github.com/animakit/animakit-expander/commit/17ae99fbb0b3afd56b1d38b20be87998ae7c5e07

Is it what you meant?

**Comment by ai** [comment]
Yeap. What do you want if we will use it by default?

**Comment by askd** [comment]
Hm, I'm not sure. But I'll think about it.
