### ISSUE TITLE
Avoid render in closed mode

### ISSUE THREAD

**Issue by ai** [animakit/animakit-expander#6]
We should save many browser memory if we will not render body in `expanded=false` mode.

We could provide extra option to render content, but default should be not “render” as I think.

**Comment by askd** [comment]
Thanks for the issue!
I reworked the component, and now it does not render children in `expanded=false` mode.
Commit: https://github.com/animakit/animakit-expander/commit/c802fcf3e23652fea42fe97916f79b299ca4fcc0
