### ISSUE TITLE
Strange animation on closed view

### ISSUE THREAD

**Issue by ai** [animakit/animakit-expander#7]
Sorry, GitHub doesn’t support webm video, I sent you a video in Slack

**Comment by askd** [comment]
Thanks for the issue. I removed initial animation.
https://github.com/animakit/animakit-elastic/commit/745558081cb6d43887815e9a1651eb7101dbffe6

**Comment by ai** [comment]
I am waiting for release :)

**Comment by askd** [comment]
Thanks for the issue. I removed initial animation.
https://github.com/animakit/animakit-expander/commit/c097e602c704cc173b946eb67614d35c4b15c33d
