### ISSUE TITLE
Привязка durationPerPx к высоте блока

### ISSUE THREAD

**Issue by sombro** [animakit/animakit-expander#9]
Было бы удобно привязать durationPerPx к высоте блока. Иначе плохо получается, например, на адаптиве: если на десктопе текст в анимируемом блоке занимал 2 строки и durationPerPx=5 смотрелся отлично, то на мобилке этот же текст занимает 10 строк и анимация выходит супер-медленной.

**Comment by askd** [comment]
Параметр durationPerPx привязан к _текущей_ высоте блока. Если высота блока меняется (10 строк вместо 2), то анимация происходит дольше.
Если вам нужна одинаковая скорость анимации при любой высоте, используйте параметр duration вместо durationPerPx.

**Comment by sombro** [comment]
Зд**о**рово, спасибо. Не догадался почитать доку непосредственно к animakit-expander на GitHub, а вот [тут](https://animakit.github.io/#/expander?_k=31dz78) про это не было ничего.
